using ABStS2Mod.Cards;
using MegaCrit.Sts2.Core.Entities.Players;
using MegaCrit.Sts2.Core.Entities.Cards;
using MegaCrit.Sts2.Core.Models;

namespace ABStS2Mod.Cards.MonsterSouls;

public static class MonsterSoulCardRegistry
{
    public static CardModel Create(Player owner, string monsterId)
    {
        string normalizedId = monsterId.StartsWith("MONSTER.") ? monsterId["MONSTER.".Length..] : monsterId;
        return normalizedId switch
        {
            "ARCHITECT" => owner.RunState.CreateCard<SoulMonsterArchitect>(owner),
            "ASSASSIN_RUBY_RAIDER" => owner.RunState.CreateCard<SoulMonsterAssassinRubyRaider>(owner),
            "ATTACK_MOVE_MONSTER" => owner.RunState.CreateCard<SoulMonsterAttackMoveMonster>(owner),
            "AXEBOT" => owner.RunState.CreateCard<SoulMonsterAxebot>(owner),
            "AXE_RUBY_RAIDER" => owner.RunState.CreateCard<SoulMonsterAxeRubyRaider>(owner),
            "BATTLE_FRIEND_V1" => owner.RunState.CreateCard<SoulMonsterBattleFriendV1>(owner),
            "BATTLE_FRIEND_V2" => owner.RunState.CreateCard<SoulMonsterBattleFriendV2>(owner),
            "BATTLE_FRIEND_V3" => owner.RunState.CreateCard<SoulMonsterBattleFriendV3>(owner),
            "BIG_DUMMY" => owner.RunState.CreateCard<SoulMonsterBigDummy>(owner),
            "BOWLBUG_EGG" => owner.RunState.CreateCard<SoulMonsterBowlbugEgg>(owner),
            "BOWLBUG_NECTAR" => owner.RunState.CreateCard<SoulMonsterBowlbugNectar>(owner),
            "BOWLBUG_ROCK" => owner.RunState.CreateCard<SoulMonsterBowlbugRock>(owner),
            "BOWLBUG_SILK" => owner.RunState.CreateCard<SoulMonsterBowlbugSilk>(owner),
            "BRUTE_RUBY_RAIDER" => owner.RunState.CreateCard<SoulMonsterBruteRubyRaider>(owner),
            "BYGONE_EFFIGY" => owner.RunState.CreateCard<SoulMonsterBygoneEffigy>(owner),
            "BYRDONIS" => owner.RunState.CreateCard<SoulMonsterByrdonis>(owner),
            "BYRDONIS_NEST" => owner.RunState.CreateCard<SoulMonsterByrdonisNest>(owner),
            "BYRDPIP" => owner.RunState.CreateCard<SoulMonsterByrdpip>(owner),
            "CALCIFIED_CULTIST" => owner.RunState.CreateCard<SoulMonsterCalcifiedCultist>(owner),
            "CEREMONIAL_BEAST" => owner.RunState.CreateCard<SoulMonsterCeremonialBeast>(owner),
            "CHOMPER" => owner.RunState.CreateCard<SoulMonsterChomper>(owner),
            "COCOON" => owner.RunState.CreateCard<SoulMonsterCocoon>(owner),
            "CORPSE_SLUG" => owner.RunState.CreateCard<SoulMonsterCorpseSlug>(owner),
            "CROSSBOW_RUBY_RAIDER" => owner.RunState.CreateCard<SoulMonsterCrossbowRubyRaider>(owner),
            "CRUSHER" => owner.RunState.CreateCard<SoulMonsterCrusher>(owner),
            "CUBEX_CONSTRUCT" => owner.RunState.CreateCard<SoulMonsterCubexConstruct>(owner),
            "DAMP_CULTIST" => owner.RunState.CreateCard<SoulMonsterDampCultist>(owner),
            "DECIMILLIPEDE_SEGMENT" => owner.RunState.CreateCard<SoulMonsterDecimillipedeSegment>(owner),
            "DEVOTED_SCULPTOR" => owner.RunState.CreateCard<SoulMonsterDevotedSculptor>(owner),
            "DOOR" => owner.RunState.CreateCard<SoulMonsterDoor>(owner),
            "DOORMAKER" => owner.RunState.CreateCard<SoulMonsterDoormaker>(owner),
            "ENTOMANCER" => owner.RunState.CreateCard<SoulMonsterEntomancer>(owner),
            "EXOSKELETON" => owner.RunState.CreateCard<SoulMonsterExoskeleton>(owner),
            "EYE_WITH_TEETH" => owner.RunState.CreateCard<SoulMonsterEyeWithTeeth>(owner),
            "FABRICATOR" => owner.RunState.CreateCard<SoulMonsterFabricator>(owner),
            "FAKE_MERCHANT_MONSTER" => owner.RunState.CreateCard<SoulMonsterFakeMerchantMonster>(owner),
            "FAT_GREMLIN" => owner.RunState.CreateCard<SoulMonsterFatGremlin>(owner),
            "FLAIL_KNIGHT" => owner.RunState.CreateCard<SoulMonsterFlailKnight>(owner),
            "FLYCONID" => owner.RunState.CreateCard<SoulMonsterFlyconid>(owner),
            "FOGMOG" => owner.RunState.CreateCard<SoulMonsterFogmog>(owner),
            "FOSSIL_STALKER" => owner.RunState.CreateCard<SoulMonsterFossilStalker>(owner),
            "FROG_KNIGHT" => owner.RunState.CreateCard<SoulMonsterFrogKnight>(owner),
            "FUZZY_WURM_CRAWLER" => owner.RunState.CreateCard<SoulMonsterFuzzyWurmCrawler>(owner),
            "GAS_BOMB" => owner.RunState.CreateCard<SoulMonsterGasBomb>(owner),
            "GAZING_MOTH" => owner.RunState.CreateCard<SoulMonsterGazingMoth>(owner),
            "GEM_EATER" => owner.RunState.CreateCard<SoulMonsterGemEater>(owner),
            "GLOBE_HEAD" => owner.RunState.CreateCard<SoulMonsterGlobeHead>(owner),
            "GREMLIN_MERC" => owner.RunState.CreateCard<SoulMonsterGremlinMerc>(owner),
            "GUARDBOT" => owner.RunState.CreateCard<SoulMonsterGuardbot>(owner),
            "HATCHLING" => owner.RunState.CreateCard<SoulMonsterHatchling>(owner),
            "HAUNTED_SHIP" => owner.RunState.CreateCard<SoulMonsterHauntedShip>(owner),
            "HUNTER_KILLER" => owner.RunState.CreateCard<SoulMonsterHunterKiller>(owner),
            "INFESTED_PRISM" => owner.RunState.CreateCard<SoulMonsterInfestedPrism>(owner),
            "INKLET" => owner.RunState.CreateCard<SoulMonsterInklet>(owner),
            "KIN_FOLLOWER" => owner.RunState.CreateCard<SoulMonsterKinFollower>(owner),
            "KIN_PRIEST" => owner.RunState.CreateCard<SoulMonsterKinPriest>(owner),
            "KNOWLEDGE_DEMON" => owner.RunState.CreateCard<SoulMonsterKnowledgeDemon>(owner),
            "LAGAVULIN_MATRIARCH" => owner.RunState.CreateCard<SoulMonsterLagavulinMatriarch>(owner),
            "LEAF_SLIME_M" => owner.RunState.CreateCard<SoulMonsterLeafSlimeM>(owner),
            "LEAF_SLIME_S" => owner.RunState.CreateCard<SoulMonsterLeafSlimeS>(owner),
            "LIVING_FOG" => owner.RunState.CreateCard<SoulMonsterLivingFog>(owner),
            "LIVING_SHIELD" => owner.RunState.CreateCard<SoulMonsterLivingShield>(owner),
            "LOUSE_PROGENITOR" => owner.RunState.CreateCard<SoulMonsterLouseProgenitor>(owner),
            "MAGI_KNIGHT" => owner.RunState.CreateCard<SoulMonsterMagiKnight>(owner),
            "MAWLER" => owner.RunState.CreateCard<SoulMonsterMawler>(owner),
            "MECHA_KNIGHT" => owner.RunState.CreateCard<SoulMonsterMechaKnight>(owner),
            "MOCK_ATTACK_AND_SUMMON_MINION_MONSTER" => owner.RunState.CreateCard<SoulMonsterMockAttackAndSummonMinionMonster>(owner),
            "MOCK_ATTACK_MONSTER" => owner.RunState.CreateCard<SoulMonsterMockAttackMonster>(owner),
            "MYSTERIOUS_KNIGHT" => owner.RunState.CreateCard<SoulMonsterMysteriousKnight>(owner),
            "MYTE" => owner.RunState.CreateCard<SoulMonsterMyte>(owner),
            "NIBBIT" => owner.RunState.CreateCard<SoulMonsterNibbit>(owner),
            "NOISEBOT" => owner.RunState.CreateCard<SoulMonsterNoisebot>(owner),
            "OSTY" => owner.RunState.CreateCard<SoulMonsterOsty>(owner),
            "OVICOPTER" => owner.RunState.CreateCard<SoulMonsterOvicopter>(owner),
            "OWL_MAGISTRATE" => owner.RunState.CreateCard<SoulMonsterOwlMagistrate>(owner),
            "PAELS_LEGION" => owner.RunState.CreateCard<SoulMonsterPaelsLegion>(owner),
            "PARAFRIGHT" => owner.RunState.CreateCard<SoulMonsterParafright>(owner),
            "PHANTASMAL_GARDENER" => owner.RunState.CreateCard<SoulMonsterPhantasmalGardener>(owner),
            "PHROG_PARASITE" => owner.RunState.CreateCard<SoulMonsterPhrogParasite>(owner),
            "PUNCH_CONSTRUCT" => owner.RunState.CreateCard<SoulMonsterPunchConstruct>(owner),
            "QUEEN" => owner.RunState.CreateCard<SoulMonsterQueen>(owner),
            "ROCKET" => owner.RunState.CreateCard<SoulMonsterRocket>(owner),
            "SCROLL_OF_BITING" => owner.RunState.CreateCard<SoulMonsterScrollOfBiting>(owner),
            "SEAPUNK" => owner.RunState.CreateCard<SoulMonsterSeapunk>(owner),
            "SEWER_CLAM" => owner.RunState.CreateCard<SoulMonsterSewerClam>(owner),
            "SHRINKER_BEETLE" => owner.RunState.CreateCard<SoulMonsterShrinkerBeetle>(owner),
            "SKULKING_COLONY" => owner.RunState.CreateCard<SoulMonsterSkulkingColony>(owner),
            "SLIMED_BERSERKER" => owner.RunState.CreateCard<SoulMonsterSlimedBerserker>(owner),
            "SLITHERING_STRANGLER" => owner.RunState.CreateCard<SoulMonsterSlitheringStrangler>(owner),
            "SLUDGE_SPINNER" => owner.RunState.CreateCard<SoulMonsterSludgeSpinner>(owner),
            "SLUMBERING_BEETLE" => owner.RunState.CreateCard<SoulMonsterSlumberingBeetle>(owner),
            "SNAPPING_JAXFRUIT" => owner.RunState.CreateCard<SoulMonsterSnappingJaxfruit>(owner),
            "SNEAKY_GREMLIN" => owner.RunState.CreateCard<SoulMonsterSneakyGremlin>(owner),
            "SOUL_FYSH" => owner.RunState.CreateCard<SoulMonsterSoulFysh>(owner),
            "SOUL_NEXUS" => owner.RunState.CreateCard<SoulMonsterSoulNexus>(owner),
            "SPECTRAL_KNIGHT" => owner.RunState.CreateCard<SoulMonsterSpectralKnight>(owner),
            "SPINY_TOAD" => owner.RunState.CreateCard<SoulMonsterSpinyToad>(owner),
            "STABBOT" => owner.RunState.CreateCard<SoulMonsterStabbot>(owner),
            "TERROR_EEL" => owner.RunState.CreateCard<SoulMonsterTerrorEel>(owner),
            "TEST_SUBJECT" => owner.RunState.CreateCard<SoulMonsterTestSubject>(owner),
            "THE_ADVERSARY_MK_ONE" => owner.RunState.CreateCard<SoulMonsterTheAdversaryMkOne>(owner),
            "THE_ADVERSARY_MK_THREE" => owner.RunState.CreateCard<SoulMonsterTheAdversaryMkThree>(owner),
            "THE_ADVERSARY_MK_TWO" => owner.RunState.CreateCard<SoulMonsterTheAdversaryMkTwo>(owner),
            "THE_ARM" => owner.RunState.CreateCard<SoulMonsterTheArm>(owner),
            "THE_BELL" => owner.RunState.CreateCard<SoulMonsterTheBell>(owner),
            "THE_DREAMER" => owner.RunState.CreateCard<SoulMonsterTheDreamer>(owner),
            "THE_FORGOTTEN" => owner.RunState.CreateCard<SoulMonsterTheForgotten>(owner),
            "THE_INSATIABLE" => owner.RunState.CreateCard<SoulMonsterTheInsatiable>(owner),
            "THE_LOST" => owner.RunState.CreateCard<SoulMonsterTheLost>(owner),
            "THE_OBSCURA" => owner.RunState.CreateCard<SoulMonsterTheObscura>(owner),
            "THIEVING_HOPPER" => owner.RunState.CreateCard<SoulMonsterThievingHopper>(owner),
            "TOADPOLE" => owner.RunState.CreateCard<SoulMonsterToadpole>(owner),
            "TORCH_HEAD_AMALGAM" => owner.RunState.CreateCard<SoulMonsterTorchHeadAmalgam>(owner),
            "TOUGH_EGG" => owner.RunState.CreateCard<SoulMonsterToughEgg>(owner),
            "TRACKER_RUBY_RAIDER" => owner.RunState.CreateCard<SoulMonsterTrackerRubyRaider>(owner),
            "TUNNELER" => owner.RunState.CreateCard<SoulMonsterTunneler>(owner),
            "TURRET_OPERATOR" => owner.RunState.CreateCard<SoulMonsterTurretOperator>(owner),
            "TWIG_SLIME_M" => owner.RunState.CreateCard<SoulMonsterTwigSlimeM>(owner),
            "TWIG_SLIME_S" => owner.RunState.CreateCard<SoulMonsterTwigSlimeS>(owner),
            "TWO_TAILED_RAT" => owner.RunState.CreateCard<SoulMonsterTwoTailedRat>(owner),
            "VANTOM" => owner.RunState.CreateCard<SoulMonsterVantom>(owner),
            "VINE_SHAMBLER" => owner.RunState.CreateCard<SoulMonsterVineShambler>(owner),
            "WATERFALL_GIANT" => owner.RunState.CreateCard<SoulMonsterWaterfallGiant>(owner),
            "WRIGGLER" => owner.RunState.CreateCard<SoulMonsterWriggler>(owner),
            "ZAPBOT" => owner.RunState.CreateCard<SoulMonsterZapbot>(owner),
            _ => owner.RunState.CreateCard<SoulCaptureTest>(owner),
        };
    }
}
